; PlatformIO Configuration - ESPBasto Relay
; XIAO ESP32-C3 - Module Relais

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

; Activer USB CDC pour Serial sur XIAO ESP32-C3
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Vitesse
upload_speed = 921600
monitor_speed = 115200

; Configuration flash
board_build.flash_mode = dio
